name: list_russian_names
description: A list of Russian names, male and female.
version: 0.1.0+1
homepage: https://github.com/ALMaclaine/dart_list_russian_names

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  effective_dart: ^1.2.1
  test: ^1.14.4
